name: Build CI windowa

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows 10

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make -C 3_Implementation
    
